# Generated by Django 2.2.3 on 2019-07-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='theme_articles', to='news.Theme'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='theme',
            name='related_themes',
            field=models.ManyToManyField(blank=True, related_name='_theme_related_themes_+', to='news.Theme'),
        ),
    ]
