# Generated by Django 2.2.3 on 2019-07-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190711_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='related_themes',
        ),
        migrations.AddField(
            model_name='theme',
            name='following_themes',
            field=models.ManyToManyField(blank=True, related_name='_theme_following_themes_+', to='news.Theme'),
        ),
    ]
