# Generated by Django 2.2.3 on 2019-07-12 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190712_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='latest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='theme',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
