# Generated by Django 2.2.3 on 2019-07-12 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190712_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='latest',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
