# Generated by Django 2.2.3 on 2019-07-12 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190712_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 12, 13, 35, 7, 496189)),
        ),
        migrations.AlterField(
            model_name='latest',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 12, 13, 35, 7, 497184)),
        ),
    ]
