# Generated by Django 2.2.3 on 2019-07-12 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190712_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 12, 16, 1, 17, 67387)),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='latest',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 12, 16, 1, 17, 68385)),
        ),
        migrations.AlterField(
            model_name='theme',
            name='url',
            field=models.IntegerField(blank=True),
        ),
    ]
